import React, { useState } from 'react';
import {
  InvestigationResult,
  RiskLevel,
} from '../types/investigation';
import { useAuth } from '../context/AuthContext';
import { AttackPathGraph } from './AttackPathGraph';
import { EvidenceLedgerTable } from './EvidenceLedgerTable';
import { UrlStructuralDetails } from './UrlStructuralDetails';
import { EmergencyPlanModal } from './EmergencyPlanModal';
import { SaveReportModal } from './SaveReportModal';
import {
  ShieldAlert,
  ShieldCheck,
  AlertTriangle,
  FileCheck,
  CheckCircle2,
  HelpCircle,
  AlertOctagon,
  ArrowRight,
  Download,
  Copy,
  Check,
  RefreshCw,
  QrCode,
  Layers,
  Sparkles,
  Info,
  BookmarkPlus,
  LayoutDashboard,
} from 'lucide-react';

interface ResultViewProps {
  result: InvestigationResult;
  onReset: () => void;
  onReturnToDashboard?: () => void;
  onRequireAuth: () => void;
  reportTitle?: string;
}

export const ResultView: React.FC<ResultViewProps> = ({
  result,
  onReset,
  onReturnToDashboard,
  onRequireAuth,
  reportTitle,
}) => {
  const { user, savedReports } = useAuth();
  const [showEmergencyModal, setShowEmergencyModal] = useState(false);
  const [showSaveModal, setShowSaveModal] = useState(false);
  const [copiedReport, setCopiedReport] = useState(false);
  const [isSaved, setIsSaved] = useState(false);

  // Check if this result is already saved in user's reports list
  const existingReport = savedReports.find(
    (r) => r.result.timestamp === result.timestamp || (reportTitle && r.title === reportTitle)
  );

  const getRiskColor = (level: RiskLevel) => {
    switch (level) {
      case 'CRITICAL':
        return {
          text: 'text-red-400',
          bg: 'bg-red-950/60',
          border: 'border-red-600/50',
          badge: 'bg-red-900/60 text-red-200 border-red-500/50',
          gauge: 'bg-red-500',
        };
      case 'HIGH':
        return {
          text: 'text-amber-400',
          bg: 'bg-amber-950/60',
          border: 'border-amber-600/50',
          badge: 'bg-amber-900/60 text-amber-200 border-amber-500/50',
          gauge: 'bg-amber-500',
        };
      case 'MEDIUM':
        return {
          text: 'text-yellow-400',
          bg: 'bg-yellow-950/50',
          border: 'border-yellow-600/50',
          badge: 'bg-yellow-900/50 text-yellow-200 border-yellow-500/50',
          gauge: 'bg-yellow-500',
        };
      case 'LOW':
      default:
        return {
          text: 'text-emerald-400',
          bg: 'bg-emerald-950/60',
          border: 'border-emerald-600/50',
          badge: 'bg-emerald-900/60 text-emerald-200 border-emerald-500/50',
          gauge: 'bg-emerald-500',
        };
    }
  };

  const colors = getRiskColor(result.riskLevel);

  // Copy full report as structured markdown
  const handleCopyReport = () => {
    const report = `# TRACEZERO DIGITAL SAFETY INVESTIGATION REPORT
Timestamp: ${result.timestamp}
Assessed Risk Level: ${result.riskLevel} (Score: ${result.riskScore}/100)

## Executive Summary
${result.summary}

## Deterministic Scoring Rationale
${result.deterministicBreakdown.scoringRationale}

## 1. OBSERVED (Direct Facts from Input)
${result.verificationBoundary.observed.map((o) => `- ${o}`).join('\n')}

## 2. INFERRED (Derived Conclusions)
${result.verificationBoundary.inferred.map((i) => `- ${i}`).join('\n')}

## 3. NOT VERIFIED (Unknown / External Boundaries)
${result.verificationBoundary.notVerified.map((n) => `- ${n}`).join('\n')}

## 4. RECOMMENDED ACTIONS
${result.recommendedActions.map((a) => `[${a.priority}] ${a.action} (${a.context})`).join('\n')}

## Evidence Ledger (${result.evidenceLedger.length} items)
${result.evidenceLedger.map((e) => `• [${e.type} | ${e.confidence} Confidence] ${e.finding} -> "${e.evidence}"`).join('\n')}

---
Generated by TRACEZERO. Grounded evidence analysis without synthetic threat reputation.
`;
    navigator.clipboard.writeText(report);
    setCopiedReport(true);
    setTimeout(() => setCopiedReport(false), 2000);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-10 space-y-8">
      {/* Navigation Breadcrumb / Return to Dashboard */}
      {onReturnToDashboard && (
        <div className="flex items-center justify-between">
          <button
            onClick={onReturnToDashboard}
            className="text-xs font-semibold text-slate-400 hover:text-white transition-colors flex items-center gap-1.5"
          >
            <LayoutDashboard className="w-3.5 h-3.5 text-blue-400" />
            <span>← Back to Dashboard</span>
          </button>
          {reportTitle && (
            <span className="text-xs font-mono text-slate-400 truncate max-w-sm">
              Archived: {reportTitle}
            </span>
          )}
        </div>
      )}

      {/* Top Banner: Risk Level + Score + Actions */}
      <div
        className={`p-6 sm:p-8 rounded-2xl border ${colors.border} ${colors.bg} backdrop-blur-md shadow-2xl relative overflow-hidden`}
      >
        <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-6">
          {/* Risk Level and Score */}
          <div className="flex flex-col sm:flex-row sm:items-center gap-6">
            {/* Score Ring / Badge */}
            <div className="flex items-center gap-4">
              <div className="relative w-24 h-24 rounded-2xl bg-slate-950/90 border border-slate-800 flex flex-col items-center justify-center shrink-0 shadow-inner">
                <span className="text-[10px] font-mono uppercase tracking-widest text-slate-400">
                  RISK SCORE
                </span>
                <span className={`text-3xl font-extrabold font-mono ${colors.text}`}>
                  {result.riskScore}
                </span>
                <span className="text-[10px] text-slate-500 font-mono">out of 100</span>
              </div>

              <div>
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs font-mono uppercase tracking-wider text-slate-400">
                    RISK LEVEL:
                  </span>
                  <span
                    className={`font-mono text-xs font-extrabold uppercase px-2.5 py-0.5 rounded border ${colors.badge}`}
                  >
                    {result.riskLevel}
                  </span>
                </div>
                <h2 className="text-xl sm:text-2xl font-bold text-white tracking-tight">
                  {result.riskLevel === 'CRITICAL' && 'Severe Credential or Deception Risk'}
                  {result.riskLevel === 'HIGH' && 'High-Probability Phishing or Threat Vector'}
                  {result.riskLevel === 'MEDIUM' && 'Caution Advised: Unverified Artifact'}
                  {result.riskLevel === 'LOW' && 'Low Risk: Consistent with Expected Communication'}
                </h2>
                <p className="text-xs sm:text-sm text-slate-300 mt-1 max-w-2xl leading-relaxed">
                  {result.summary}
                </p>
              </div>
            </div>
          </div>

          {/* Action Buttons: Save, Emergency & Export */}
          <div className="flex flex-wrap sm:flex-nowrap items-center gap-2.5 shrink-0">
            {/* Save Report button */}
            <button
              onClick={() => setShowSaveModal(true)}
              disabled={isSaved || Boolean(existingReport)}
              className={`w-full sm:w-auto px-4 py-2.5 rounded-xl text-xs font-semibold transition-colors flex items-center justify-center gap-1.5 shadow-md cursor-pointer ${
                isSaved || existingReport
                  ? 'bg-emerald-950/60 border border-emerald-700/60 text-emerald-300 cursor-default'
                  : 'bg-blue-600 hover:bg-blue-500 text-white shadow-blue-900/40'
              }`}
            >
              {isSaved || existingReport ? (
                <>
                  <Check className="w-4 h-4 text-emerald-400" />
                  <span>Saved in Dashboard</span>
                </>
              ) : (
                <>
                  <BookmarkPlus className="w-4 h-4" />
                  <span>Save Report</span>
                </>
              )}
            </button>

            {/* "I already interacted with it" Emergency Button */}
            <button
              onClick={() => setShowEmergencyModal(true)}
              className="w-full sm:w-auto px-3.5 py-2.5 rounded-xl text-xs font-semibold bg-amber-600 hover:bg-amber-500 text-white transition-colors flex items-center justify-center gap-1.5 shadow-lg shadow-amber-950/40 cursor-pointer"
            >
              <ShieldAlert className="w-4 h-4" />
              <span>I interacted with it</span>
            </button>

            <button
              onClick={handleCopyReport}
              className="w-full sm:w-auto px-3 py-2.5 rounded-xl text-xs font-medium border border-slate-700 bg-slate-900/80 hover:bg-slate-800 text-slate-200 transition-colors flex items-center justify-center gap-1.5"
              title="Copy markdown report"
            >
              {copiedReport ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copiedReport ? 'Copied' : 'Export'}</span>
            </button>

            <button
              onClick={onReset}
              className="w-full sm:w-auto px-3 py-2.5 rounded-xl text-xs font-medium border border-slate-700 bg-slate-900/80 hover:bg-slate-800 text-slate-200 transition-colors flex items-center justify-center gap-1.5"
            >
              <RefreshCw className="w-3.5 h-3.5" />
              <span>New</span>
            </button>
          </div>
        </div>

        {/* Deterministic Scoring Engine Explainer */}
        <div className="mt-5 pt-4 border-t border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-[11px] text-slate-300 font-mono">
          <div className="flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-blue-400 shrink-0" />
            <span>Deterministic Rationale: {result.deterministicBreakdown.scoringRationale}</span>
          </div>
          <span className="text-slate-400 shrink-0">
            Formula: ∑(Triggered Verified Weights) Normalized
          </span>
        </div>
      </div>

      {/* CORE 4-PILLAR REASONING SECTIONS:
          1. OBSERVED
          2. INFERRED
          3. NOT VERIFIED
          4. RECOMMENDED ACTION */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {/* 1. OBSERVED */}
        <div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/80 shadow-lg space-y-3">
          <div className="flex items-center gap-2 border-b border-slate-800 pb-2.5">
            <div className="w-6 h-6 rounded-md bg-blue-950/80 border border-blue-500/40 flex items-center justify-center text-blue-400">
              <CheckCircle2 className="w-3.5 h-3.5" />
            </div>
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 font-mono">
                1. OBSERVED
              </h3>
              <p className="text-[11px] text-slate-400">
                Facts directly visible in the supplied input
              </p>
            </div>
          </div>

          <ul className="space-y-2 text-xs text-slate-200 leading-relaxed font-sans">
            {result.verificationBoundary.observed.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2 bg-slate-950/50 p-2.5 rounded-lg border border-slate-800/60">
                <span className="text-blue-400 font-mono text-[10px] mt-0.5">•</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* 2. INFERRED */}
        <div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/80 shadow-lg space-y-3">
          <div className="flex items-center gap-2 border-b border-slate-800 pb-2.5">
            <div className="w-6 h-6 rounded-md bg-amber-950/80 border border-amber-500/40 flex items-center justify-center text-amber-400">
              <HelpCircle className="w-3.5 h-3.5" />
            </div>
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 font-mono">
                2. INFERRED
              </h3>
              <p className="text-[11px] text-slate-400">
                Reasonable conclusions derived from observations
              </p>
            </div>
          </div>

          <ul className="space-y-2 text-xs text-slate-200 leading-relaxed font-sans">
            {result.verificationBoundary.inferred.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2 bg-slate-950/50 p-2.5 rounded-lg border border-slate-800/60">
                <span className="text-amber-400 font-mono text-[10px] mt-0.5">↳</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* 3. NOT VERIFIED */}
        <div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/80 shadow-lg space-y-3">
          <div className="flex items-center gap-2 border-b border-slate-800 pb-2.5">
            <div className="w-6 h-6 rounded-md bg-slate-800 border border-slate-700 flex items-center justify-center text-slate-300">
              <AlertTriangle className="w-3.5 h-3.5 text-slate-400" />
            </div>
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 font-mono">
                3. NOT VERIFIED
              </h3>
              <p className="text-[11px] text-slate-400">
                Crucial factors that cannot be established from input alone
              </p>
            </div>
          </div>

          <ul className="space-y-2 text-xs text-slate-300 leading-relaxed font-sans">
            {result.verificationBoundary.notVerified.map((item, idx) => (
              <li key={idx} className="flex items-start gap-2 bg-slate-950/50 p-2.5 rounded-lg border border-slate-800/60">
                <span className="text-slate-500 font-mono text-[10px] mt-0.5">?</span>
                <span className="text-slate-400">{item}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* 4. RECOMMENDED ACTION */}
        <div className="p-5 rounded-2xl border border-slate-800 bg-slate-900/80 shadow-lg space-y-3">
          <div className="flex items-center gap-2 border-b border-slate-800 pb-2.5">
            <div className="w-6 h-6 rounded-md bg-emerald-950/80 border border-emerald-500/40 flex items-center justify-center text-emerald-400">
              <FileCheck className="w-3.5 h-3.5" />
            </div>
            <div>
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 font-mono">
                4. RECOMMENDED ACTIONS
              </h3>
              <p className="text-[11px] text-slate-400">
                Concrete defensive steps user should execute
              </p>
            </div>
          </div>

          <div className="space-y-2.5">
            {result.recommendedActions.map((act, idx) => (
              <div
                key={idx}
                className="p-2.5 rounded-lg border border-slate-800/80 bg-slate-950/60 flex items-start gap-2.5 text-xs"
              >
                <span
                  className={`text-[9px] font-mono uppercase font-bold px-1.5 py-0.5 rounded mt-0.5 ${
                    act.priority === 'IMMEDIATE'
                      ? 'bg-red-950 text-red-300 border border-red-800'
                      : act.priority === 'HIGH'
                      ? 'bg-amber-950 text-amber-300 border border-amber-800'
                      : 'bg-blue-950 text-blue-300 border border-blue-800'
                  }`}
                >
                  {act.priority}
                </span>
                <div>
                  <span className="font-semibold text-slate-200 block">{act.action}</span>
                  <span className="text-[11px] text-slate-400">{act.context}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* QR DECODED DETAIL (if QR present) */}
      {result.qrDetails && (
        <div className="p-5 rounded-2xl border border-purple-900/40 bg-purple-950/20 shadow-lg space-y-2">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <QrCode className="w-4 h-4 text-purple-400" />
              <h4 className="text-xs font-bold uppercase tracking-wider text-purple-300 font-mono">
                DECODED QR CODE MATRIX PAYLOAD
              </h4>
            </div>
            <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-purple-900/50 text-purple-300 border border-purple-700/50">
              Locally Decoded
            </span>
          </div>
          <div className="p-3 rounded-xl bg-slate-950 border border-purple-900/40 font-mono text-xs text-slate-200 break-all select-all">
            {result.qrDetails.rawText}
          </div>
          <p className="text-[11px] text-purple-300/80">
            Raw payload extracted directly from matrix pixels without sending image to third-party APIs.
          </p>
        </div>
      )}

      {/* LOCAL URL FORENSICS COMPONENT */}
      {result.urlAnalysis && (
        <UrlStructuralDetails urlAnalysis={result.urlAnalysis} />
      )}

      {/* EVIDENCE-GROUNDED ATTACK PROGRESSION GRAPH */}
      <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/80 shadow-lg">
        <AttackPathGraph steps={result.attackPath} />
      </div>

      {/* EVIDENCE LEDGER */}
      <div className="p-6 rounded-2xl border border-slate-800 bg-slate-900/80 shadow-lg">
        <EvidenceLedgerTable evidenceLedger={result.evidenceLedger} />
      </div>

      {/* False Positive Considerations */}
      {result.falsePositiveConsiderations && result.falsePositiveConsiderations.length > 0 && (
        <div className="p-5 rounded-2xl border border-slate-800 bg-slate-950/60 text-xs space-y-2">
          <div className="flex items-center gap-2 text-slate-300 font-mono font-bold text-xs uppercase tracking-wider">
            <Info className="w-4 h-4 text-blue-400" />
            False Positive Considerations & Benign Contexts:
          </div>
          <ul className="space-y-1 text-slate-400 text-xs list-disc list-inside">
            {result.falsePositiveConsiderations.map((fp, i) => (
              <li key={i}>{fp}</li>
            ))}
          </ul>
        </div>
      )}

      {/* AI Contextual Reasoning (Groq) */}
      <div className="p-5 rounded-2xl border border-purple-900/40 bg-purple-950/20 text-xs space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-purple-400" />
            <h4 className="text-xs font-bold uppercase tracking-wider text-purple-300 font-mono">
              CONTEXTUAL AI REASONING
            </h4>
          </div>
          <span
            className={`text-[10px] font-mono px-2 py-0.5 rounded border ${
              result.aiReasoningStatus.available
                ? 'bg-emerald-950/60 text-emerald-300 border-emerald-700/50'
                : 'bg-slate-800 text-slate-400 border-slate-700'
            }`}
          >
            {result.aiReasoningStatus.available ? 'Groq Connected' : 'Unavailable — deterministic analysis remains active'}
          </span>
        </div>

        {result.aiInterpretation ? (
          <div className="space-y-3">
            <div className="p-3 rounded-xl bg-slate-950 border border-purple-900/40">
              <p className="text-slate-200 font-semibold mb-1">{result.aiInterpretation.summary}</p>
              <p className="text-slate-400 text-[11px] leading-relaxed">{result.aiInterpretation.contextualExplanation}</p>
            </div>

            {result.aiInterpretation.attackPathWording && result.aiInterpretation.attackPathWording.length > 0 && (
              <div>
                <p className="text-[10px] text-purple-300/80 font-mono uppercase mb-1.5">Attack Path Context</p>
                <ul className="space-y-1 text-slate-300 text-[11px] list-disc list-inside">
                  {result.aiInterpretation.attackPathWording.map((phrase, i) => (
                    <li key={i}>{phrase}</li>
                  ))}
                </ul>
              </div>
            )}

            {result.aiInterpretation.defensiveActions && result.aiInterpretation.defensiveActions.length > 0 && (
              <div>
                <p className="text-[10px] text-purple-300/80 font-mono uppercase mb-1.5">AI-Recommended Defensive Actions</p>
                <ul className="space-y-1 text-slate-300 text-[11px] list-disc list-inside">
                  {result.aiInterpretation.defensiveActions.map((action, i) => (
                    <li key={i}>{action}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
        ) : (
          <p className="text-slate-400 text-[11px] italic">
            {result.aiReasoningStatus.available
              ? 'Contextual reasoning is being processed...'
              : 'Contextual AI reasoning is unavailable. Deterministic evidence analysis is still available.'}
          </p>
        )}
      </div>

      {/* Investigation Memory (Breeth) */}
      <div className="p-5 rounded-2xl border border-cyan-900/40 bg-cyan-950/20 text-xs space-y-2">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Layers className="w-4 h-4 text-cyan-400" />
            <h4 className="text-xs font-bold uppercase tracking-wider text-cyan-300 font-mono">
              INVESTIGATION MEMORY
            </h4>
          </div>
          <span
            className={`text-[10px] font-mono px-2 py-0.5 rounded border ${
              result.memoryStatus.available
                ? 'bg-emerald-950/60 text-emerald-300 border-emerald-700/50'
                : 'bg-slate-800 text-slate-400 border-slate-700'
            }`}
          >
            {result.memoryStatus.available ? 'Breeth Connected' : 'Unavailable — current analysis remains active'}
          </span>
        </div>
        <p className="text-slate-400 text-[11px]">
          {result.memoryStatus.available
            ? 'This investigation was stored in external memory for pattern recognition across sessions.'
            : 'Memory service unavailable. This investigation was analyzed locally.'}
        </p>
      </div>

      {/* Emergency Incident Containment Modal */}
      <EmergencyPlanModal
        isOpen={showEmergencyModal}
        onClose={() => setShowEmergencyModal(false)}
        threatSummary={result.summary}
        riskLevel={result.riskLevel}
      />

      {/* Save Report Modal */}
      <SaveReportModal
        isOpen={showSaveModal}
        onClose={() => setShowSaveModal(false)}
        result={result}
        onSaved={() => setIsSaved(true)}
        onRequireAuth={onRequireAuth}
      />
    </div>
  );
};

